routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('migrate', function () {
  return \Artisan::call('migrate');
});



Route::get('super-admin-seed', function () {
  return \Artisan::call('db:seed --class=SuperAdminSeeder');
});



Route::get('storage', function () {
  return \Artisan::call('storage:link');
});

Route::group(['namespace' => 'App\Http\Controllers'], function () {

  // --------------------  Super-Admin----------------

  Route::group(['prefix' => 'management-control', 'as' => 'super.admin.', 'namespace' => 'Superadmin'], function () {

    Route::get('/login', 'LoginController@index')->name('login');
    Route::post('/login', 'LoginController@login')->name('login');

    Route::group(['middleware' => 'superadmin'], function () {

      Route::get('/logout', 'LoginController@logout')->name('logout');
      Route::get('/', 'DashboardController@dashboard')->name('dashboard');
      Route::get('editprofile', 'EditprofileController@index')->name('editprofile');
      // Route::get('sitesetting', 'SiteController@index')->name('sitesetting');
      Route::get('changepassword', 'ChangepasswordController@index')->name('changepassword');
      Route::post('changepassword', 'ChangepasswordController@update');



      Route::resources([
        'site'          => 'SiteController',
        'template'      => 'TemplateController',
        'posttype'      => 'PosttypeController',
        'menulocation'  => 'MenuLocationController',
        'admin'         => 'AdminController',
        'permission'    => 'PermissionController',
      ]);
    });
  });

  // ------------------   Admin-----------------------

  Route::group(['prefix' => 'admin-control', 'as' => 'admin.'], function () {

    Route::get('/login', 'LoginController@index')->name('login');
    Route::post('/login', 'LoginController@login')->name('login');

    Route::group(['middleware' => 'admin'], function () {
      Route::get('export', 'ExportController@index')->name('export');

      Route::get('/logout', 'LoginController@logout')->name('logout');
      Route::get('/', 'DashboardController@dashboard')->name('dashboard');
      Route::get('editprofile', 'EditprofileController@index')->name('editprofile');
      Route::get('changepassword', 'ChangepasswordController@index')->name('changepassword');
      Route::get('sitesetting', 'SiteController@index')->name('sitesetting');

      Route::post('sitesetting', 'SiteController@store')->name('site.store');
      Route::get('menu_item/delete', 'MenuItemController@destroy')->name('menu_item.destroy');

      // Route::get('menu', 'SelectmenuController@create')->name('menu.create');
      // Route::get('menu', 'SelectmenuController@index')->name('menu.index');
      // Route::get('menuit', 'MenuController@create')->name('menuit.create');
      // Route::get('menuit', 'MenuController@index')->name('menuit.index');

      Route::resources([
        'menu'      => 'MenuController',
        'menu-item' => 'MenuItemController',
        'media'     =>  'MediaController',
        'contact'     =>  'EnquiaryController',
      ]);

      Route::post('menu-item/sort', 'MenuItemController@updateSort')->name('menu-item.update.sort');

      Route::get('category/{post_type:slug}', 'CategoryController@index')->name('category.index');
      Route::get('category/{post_type:slug}/create', 'CategoryController@create')->name('category.create');
      Route::get('category/{post_type:slug}/edit/{category:slug}', 'CategoryController@edit')->name('category.edit');
      Route::put('category/{post_type:slug}/update/{category:slug}', 'CategoryController@update')->name('category.update');
      Route::delete('category/{post_type:slug}/delete/{category:slug}', 'CategoryController@destroy')->name('category.destroy');
      Route::post('category/{post_type:slug}/store', 'CategoryController@store')->name('category.store');


      Route::get('{post_type:slug}', 'PostController@index')->name('post.index');
      Route::get('{post_type:slug}/create', 'PostController@create')->name('post.create');
      Route::get('{post_type:slug}/edit/{post:slug}', 'PostController@edit')->name('post.edit');
      Route::put('{post_type:slug}/update/{post:slug}', 'PostController@update')->name('post.update');
      Route::delete('{post_type:slug}/delete/{post:slug}', 'PostController@destroy')->name('post.destroy');
      Route::post('{post_type:slug}/store', 'PostController@store')->name('post.store');
    });
  });

  # Web Routes
  Route::group(['namespace' => 'Web'], function () {

    Route::get('/', 'PostController@show')->name('home');
    Route::post('/contactas', 'ContactUsController@store')->name('contact.store');
    Route::post('/contact', 'ContactUsController@sendEnquiry')->name('contact.send');
    Route::post('/registration', 'RegistrationController@sendEnquiry')->name('registration.send');
    Route::get('/{post:slug}', 'PostController@show')->name('post.show');
  });

  Route::get('send-mail', function () {

    $details = [
      'title' => 'Mail from ItSolutionStuff.com',
      'body' => 'This is for testing email using smtp'
    ];

    \Mail::to('your_receiver_email@gmail.com')->send(new \App\Mail\MyContactMail($details));

    dd("Email is Sent.");
  });
});

app/Http/Controllers/EnquiaryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Enquiry;
use Illuminate\Http\Request;

class EnquiaryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $type = request('type');
        $data = Enquiry::where('type', $type)->paginate(10);

        return view('backend.pages.enquiary.index', compact('data', 'type'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Enquiry $contact)

    {
        // dd($contactenq->details);
        $details =  $contact->details;
        // dd($details);
        $details['site'] = (object) $details['site'];
        // return view( $enquiary->email_template, $details);

        return view('backend.pages.enquiary.show', compact('details', 'contact'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $media = Enquiry::findOrFail($id);
        $media->delete();
        return redirect()->back();
    }
}

resources/views/backend/pages/enquiary/index.blade.php
@extends('backend.layouts.inner')
@section('site_title','View Page')
@section('content')



<main>
                    <div class="container-fluid">
                    <h1 class="mt-4">{{ $type }}</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item">
                <a href="{{ route('admin.dashboard')  }}">Dashboard</a>
            </li>
           
            <li class="breadcrumb-item active">{{ $type }}</li>
         </ol>
                     
                        <div class="card mb-4">
                            <div class="card-header">
                                <i class="fas fa-table mr-1"></i>
                                DataTable Example
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                        <thead>
                                            <tr>
                                                <th>S.NO</th>
                                                <!-- <th>Sender</th> -->
                                                <th>Subject</th>
                                                <th>From</th>
                                                <th>To</th>
                                                <!-- <th>Receiver</th> -->
                                                <th>Type</th>
                                                <th>Date and Time</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                          @foreach($data as $key=>$da) 
                                            <tr>
                                                <td>{{$data->firstItem() + $key}}</td>
                                                <td><a href="{{route('admin.contact.show', $da->id)}}">{{$da->subject}}</a></td>
                                                <td>
                                                    <strong>{{$da->sender}}</strong><br>
                                                    ({{ $da->from }})
                                                </td>
                                                <td>
                                                    <strong>{{$da->receiver}}</strong><br>
                                                    ({{ $da->to }})
                                                </td>
                                                <td>{{$da->type}}</td>
                                                <td>
                                                    <div style="white-space: nowrap;">
                                                        {{ date("d/m/Y h:i A", strtotime($da->created_at)) }}
                                                    </div>
                                                </td>
                                                <td>  
                                                    {{ Form::open(['url' => route('admin.contact.destroy', [$da->id]), 'method' => 'delete']) }}
                                                    <button class="btn btn-sm btn-danger">Delete</button>
                                                    {{ Form::close() }}
                                                </td>                                             
                                            </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
        @endsection

resources/views/backend/pages/enquiary/show.blade.php
@extends('backend.layouts.inner')
@section('site_title','View Page')
@section('content')



<main style="padding: 50px;">
           @include($contact->email_template, $details)       
                </main>
        @endsection