routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('migrate', function () {
  return \Artisan::call('migrate');
});



Route::get('super-admin-seed', function () {
  return \Artisan::call('db:seed --class=SuperAdminSeeder');
});



Route::get('storage', function () {
  return \Artisan::call('storage:link');
});

Route::group(['namespace' => 'App\Http\Controllers'], function () {

  // --------------------  Super-Admin----------------

  Route::group(['prefix' => 'management-control', 'as' => 'super.admin.', 'namespace' => 'Superadmin'], function () {

    Route::get('/login', 'LoginController@index')->name('login');
    Route::post('/login', 'LoginController@login')->name('login');

    Route::group(['middleware' => 'superadmin'], function () {

      Route::get('/logout', 'LoginController@logout')->name('logout');
      Route::get('/', 'DashboardController@dashboard')->name('dashboard');
      Route::get('editprofile', 'EditprofileController@index')->name('editprofile');
      // Route::get('sitesetting', 'SiteController@index')->name('sitesetting');
      Route::get('changepassword', 'ChangepasswordController@index')->name('changepassword');
      Route::post('changepassword', 'ChangepasswordController@update');



      Route::resources([
        'site'          => 'SiteController',
        'template'      => 'TemplateController',
        'posttype'      => 'PosttypeController',
        'menulocation'  => 'MenuLocationController',
        'admin'         => 'AdminController',
        'permission'    => 'PermissionController',
      ]);
    });
  });

  // ------------------   Admin-----------------------

  Route::group(['prefix' => 'admin-control', 'as' => 'admin.'], function () {

    Route::get('/login', 'LoginController@index')->name('login');
    Route::post('/login', 'LoginController@login')->name('login');

    Route::group(['middleware' => 'admin'], function () {
      Route::get('export', 'ExportController@index')->name('export');

      Route::get('/logout', 'LoginController@logout')->name('logout');
      Route::get('/', 'DashboardController@dashboard')->name('dashboard');
      Route::get('editprofile', 'EditprofileController@index')->name('editprofile');
      Route::get('changepassword', 'ChangepasswordController@index')->name('changepassword');
      Route::get('sitesetting', 'SiteController@index')->name('sitesetting');

      Route::post('sitesetting', 'SiteController@store')->name('site.store');
      Route::get('menu_item/delete', 'MenuItemController@destroy')->name('menu_item.destroy');

      // Route::get('menu', 'SelectmenuController@create')->name('menu.create');
      // Route::get('menu', 'SelectmenuController@index')->name('menu.index');
      // Route::get('menuit', 'MenuController@create')->name('menuit.create');
      // Route::get('menuit', 'MenuController@index')->name('menuit.index');

      Route::resources([
        'menu'      => 'MenuController',
        'menu-item' => 'MenuItemController',
        'media'     =>  'MediaController',
        'contact'     =>  'EnquiaryController',
      ]);

      Route::post('menu-item/sort', 'MenuItemController@updateSort')->name('menu-item.update.sort');

      Route::get('category/{post_type:slug}', 'CategoryController@index')->name('category.index');
      Route::get('category/{post_type:slug}/create', 'CategoryController@create')->name('category.create');
      Route::get('category/{post_type:slug}/edit/{category:slug}', 'CategoryController@edit')->name('category.edit');
      Route::put('category/{post_type:slug}/update/{category:slug}', 'CategoryController@update')->name('category.update');
      Route::delete('category/{post_type:slug}/delete/{category:slug}', 'CategoryController@destroy')->name('category.destroy');
      Route::post('category/{post_type:slug}/store', 'CategoryController@store')->name('category.store');


      Route::get('{post_type:slug}', 'PostController@index')->name('post.index');
      Route::get('{post_type:slug}/create', 'PostController@create')->name('post.create');
      Route::get('{post_type:slug}/edit/{post:slug}', 'PostController@edit')->name('post.edit');
      Route::put('{post_type:slug}/update/{post:slug}', 'PostController@update')->name('post.update');
      Route::delete('{post_type:slug}/delete/{post:slug}', 'PostController@destroy')->name('post.destroy');
      Route::post('{post_type:slug}/store', 'PostController@store')->name('post.store');
    });
  });

  # Web Routes
  Route::group(['namespace' => 'Web'], function () {

    Route::get('/', 'PostController@show')->name('home');
    Route::post('/contactas', 'ContactUsController@store')->name('contact.store');
    Route::post('/contact', 'ContactUsController@sendEnquiry')->name('contact.send');
    Route::post('/registration', 'RegistrationController@sendEnquiry')->name('registration.send');
    Route::get('/{post:slug}', 'PostController@show')->name('post.show');
  });

  Route::get('send-mail', function () {

    $details = [
      'title' => 'Mail from ItSolutionStuff.com',
      'body' => 'This is for testing email using smtp'
    ];

    \Mail::to('your_receiver_email@gmail.com')->send(new \App\Mail\MyContactMail($details));

    dd("Email is Sent.");
  });
});

app/Models/Permission.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Permission extends Model
{
    use HasFactory;

    public function permission_data()
    {
        return $this->hasMany(PermissionData::class);
    }
}

app/Http/Controllers/Superadmin/PermissionController.php
<?php

namespace App\Http\Controllers\Superadmin;

use App\Http\Controllers\Controller;
use App\Models\Permission;
use Illuminate\Http\Request;
use App\Models\Site;
use App\Models\Posttype;
use App\Models\Admin;
use App\Models\PermissionData;

class PermissionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $request->flush();
        $admin = Admin::pluck('name', 'id');
        $themes = Site::pluck('domain', 'id');
        $all_post_types = PostType::pluck('name', 'slug');
        return view('superadmin.pages.permission.create', compact('all_post_types', 'themes', 'admin'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $p_query = Permission::where('site_id', $request->site_id)->where('admin_id', $request->admin_id);

        $permission = $p_query->count() ? $p_query->first() : new Permission();
        $permission->site_id = $request->site_id;
        $permission->admin_id = $request->admin_id;
        // $permission->name = $request->name;

        $permission->save();

        PermissionData::where('permission_id', $permission->id)->delete();

        foreach ($request->names as $name) {
            $permission_data = new PermissionData();
            $permission_data->permission_id = $permission->id;
            $permission_data->name = $name;
            $permission_data->save();
        }

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Permission  $permission
     * @return \Illuminate\Http\Response
     */
    public function show(Permission $permission)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Permission  $permission
     * @return \Illuminate\Http\Response
     */
    public function edit(Permission $permission)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Permission  $permission
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Permission $permission)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Permission  $permission
     * @return \Illuminate\Http\Response
     */
    public function destroy(Permission $permission)
    {
        //
    }
}

resources/views/superadmin/pages/permission/create.blade.php
@extends('superadmin.layouts.inner')
@section('site_title','Add Permission')
@section('content')

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Add Permission</h1>
        <ol class="breadcrumb mb-4">  
            <li class="breadcrumb-item">
                <a href="{{ route('super.admin.dashboard')}}">Dashboard</a>
            </li>        
            <li class="breadcrumb-item">
                <a href="{{ route('super.admin.permission.index')}}">Permission</a>
            </li>
            <li class="breadcrumb-item active">Add Permission</li>
        </ol>

            {{ Form::open([
                'url' => route('super.admin.permission.store'),
                'files' => true, 
                'method' => 'post',
                'class' =>'needs-validation',
                'novalidate' =>'true',
            ]) }}
    <!-- DataTales Example -->
    <div class="row">
        <div class="col-sm-8 col-lg-9">
            
                    @include('superadmin.pages.permission.form')
        </div>
        <div class="col-sm-4 col-lg-3">
            <div class="card">
                <div class="card-body"style="text-align: center;padding: 32px;">
                    <button class="btn btn-primary">
                        Save
                    </button>
                    <button type="reset" class="btn btn-secondary">
                        Reset
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
{{ Form::close() }}

</div>
@endsection

resources/views/superadmin/pages/permission/form.blade.php
<div class="mb-3">
    {{Form::label('site_id','Site', null, ['class' =>'form-label'])}}
    {{Form::select('site_id',$themes,null , ['class' => 'form-select', 'placeholder'=> 'Select Site', 'autocomplete' => 'off']) }}
</div>

<div class="mb-3">
    {{Form::label('admin_id','Admin', null, ['class' =>'form-label'])}}
    {{Form::select('admin_id',$admin,null , ['class' => 'form-select', 'placeholder'=> 'Select Site', 'autocomplete' => 'off']) }}
</div>

<div class="mb-3 ">
    {{Form::label('menu','Menu', null, ['class' =>'form-label'])}} 
      <label class="switch">
        <input type="checkbox" name="names[]" value="menu">
        <span class="slider round"></span>
      </label>
     <br>
    {{Form::label('media','Media', null, ['class' =>'form-label'])}}
    <label class="switch">
        <input type="checkbox"  name="names[]" value="media">
        <span class="slider round"></span>
      </label>
      @foreach($all_post_types as $pid => $pname)
      <br>
      <label for="names_{{$pid}}" >Add {{$pname}}</label>
     <label class="switch">
         <input type="checkbox"  name="names[]" value="Add {{$pname}}" id="names_{{$pid}}">
         <span class="slider round"></span>
       </label>

       <br>
       <label for="names_view_{{$pid}}" >View {{$pname}}</label>
      <label class="switch">
          <input type="checkbox"  name="names[]" value="View {{$pname}}" id="names_view_{{$pid}}">
          <span class="slider round"></span>
        </label>
       @endforeach
</div>